version: "2.4"
services:
  server:
    image: mox-server
    ports:
      - "9898:9898"
    networks:
      - mox-server-network
    healthcheck:
      test: ["CMD", "curl", "-f", "server:9898/healthcheck"]
      interval: 1s
      timeout: 10s
      retries: 10
  initializer:
    image: curlimages/curl
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - .:/data
    command: ["sh","-c","sleep 8 && echo calling service && curl -X POST server:9898/endpoints -H 'Content-Type: application/json' --data-binary '@data/endpoints-schema-example.json' "]    
    networks:
      - mox-server-network
networks:
  mox-server-network: